language: python
python:
- '2.7'
install:
- pip install django
- mkdir repo
- django-admin.py startproject --extension=py,.gitignore --template=https://github.com/datadesk/django-project-template/archive/master.zip project repo
- cd repo
- pip install -r requirements.txt
- cp project/settings_test.template project/settings_dev.py
script:
- pep8 toolbox
- pyflakes toolbox
- coverage run setup.py test
after_success:
  - coveralls
